microservice-chart:
  namespace: "payopt"
  nameOverride: ""
  fullnameOverride: "payment-options"
  image:
    repository: ghcr.io/pagopa/pagopa-payment-options
    tag: "0.4.1"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /q/health/live
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /q/health/ready
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "paymentoptions.itn.internal.dev.platform.pagopa.it"
    path: /pagopa-payment-options-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    capabilities:
      drop:
        - all
  tmpVolumeMount:
    create: true
    mounts:
      - name: temp
        mountPath: /temp
      - name: logs
        mountPath: /logs
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.5"
    limits:
      memory: "512Mi"
      cpu: "0.5"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    APP_NAME: "payment-options-service"
    APP_ENVIRONMENT: "dev"
    WEBSITE_SITE_NAME: 'payment-options-service' # required to show cloud role name in application insights
    APP_LOGGING_LEVEL: 'DEBUG'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    APICONFIG_CACHE_URL: 'https://api.dev.platform.pagopa.it/api-config-cache/o/v1'
    CACHE_EVT_HOST: 'pagopa-d-weu-core-evh-ns04.servicebus.windows.net'
    CACHE_EVT_TOPIC: 'nodo-dei-pagamenti-cache'
    VERIFY_KO_EVT_HOST: 'pagopa-d-weu-core-evh-ns03.servicebus.windows.net'
    VERIFY_KO_EVT_TOPIC: 'nodo-dei-pagamenti-verify-ko'
    VERIFY_RE_EVT_HOST: 'pagopa-d-itn-payopt-evh.servicebus.windows.net'
    VERIFY_RE_EVT_TOPIC: 'pagopa-payopt-evh'
  envSecret:
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'app-insight-connection-string'
    KAFKA_EH_CACHE_JAAS_CONFIG: "ehub-d-nodo-pagamenti-cache-jaas-config"
    KAFKA_VERIFY_KO_JAAS_CONFIG: "ehub-d-nodo-dei-pagamenti-verify-ko-jaas-config"
    KAFKA_EH_RE_JAAS_CONFIG: "ehub-d-payment-options-re-jaas-config"
    APICONFIG_SUBKEY: "api-config-sub-key"
    EC_APIM_SUBKEY: "forwarder-sub-key"
  keyvault:
    name: "pagopa-d-itn-paymentoptions-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-payment-options-service
        tag: "0.0.0"
        pullPolicy: Always
      envConfig: {}
      envSecret: {}
